//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App6.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App6.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string AppError {
            get {
                return ResourceManager.GetString("AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occurred. Please check your internet connection or correct your input and try again. ähnelt.
        /// </summary>
        internal static string AppErrorMsg {
            get {
                return ResourceManager.GetString("AppErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CANCEL ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Surveys ähnelt.
        /// </summary>
        internal static string CreateSurvey {
            get {
                return ResourceManager.GetString("CreateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy statement ähnelt.
        /// </summary>
        internal static string DatenschutzButton {
            get {
                return ResourceManager.GetString("DatenschutzButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please answer the red marked question item(s). ähnelt.
        /// </summary>
        internal static string FieldsUnfilled {
            get {
                return ResourceManager.GetString("FieldsUnfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Information ähnelt.
        /// </summary>
        internal static string InformationButton {
            get {
                return ResourceManager.GetString("InformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to save the data? ähnelt.
        /// </summary>
        internal static string InformationSaveQuery {
            get {
                return ResourceManager.GetString("InformationSaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LANGUAGE ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login credentials are incorrect! ähnelt.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login is currently not possible. Please try again later. ähnelt.
        /// </summary>
        internal static string LoginNotAvailable {
            get {
                return ResourceManager.GetString("LoginNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login is not available until 1 October 2019. Please try again later. ähnelt.
        /// </summary>
        internal static string LoginNotYetAvailable {
            get {
                return ResourceManager.GetString("LoginNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LOGIN ähnelt.
        /// </summary>
        internal static string LoginPageHeadline {
            get {
                return ResourceManager.GetString("LoginPageHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have been successfully registered. ähnelt.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are using an outdated app version, please update your app via the Google Play Store. ähnelt.
        /// </summary>
        internal static string LoginWrongAppVersion {
            get {
                return ResourceManager.GetString("LoginWrongAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password should contain at least one number (0-9) and one sign (like @, §, $, %, #). ähnelt.
        /// </summary>
        internal static string PasswordLowComplexity {
            get {
                return ResourceManager.GetString("PasswordLowComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password and confirmation password do not match. ähnelt.
        /// </summary>
        internal static string PasswordNoMatch {
            get {
                return ResourceManager.GetString("PasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password is too short. Minimum length is 6 character. ähnelt.
        /// </summary>
        internal static string PasswordShort {
            get {
                return ResourceManager.GetString("PasswordShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preferences ähnelt.
        /// </summary>
        internal static string PreferenceLabel {
            get {
                return ResourceManager.GetString("PreferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username: ähnelt.
        /// </summary>
        internal static string PreferenceLabelBenutzername {
            get {
                return ResourceManager.GetString("PreferenceLabelBenutzername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User role: ähnelt.
        /// </summary>
        internal static string PreferenceLabelBenutzerrolle {
            get {
                return ResourceManager.GetString("PreferenceLabelBenutzerrolle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Institution: ähnelt.
        /// </summary>
        internal static string PreferenceLabelEinrichtung {
            get {
                return ResourceManager.GetString("PreferenceLabelEinrichtung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Institution area: ähnelt.
        /// </summary>
        internal static string PreferenceLabelWohnbereich {
            get {
                return ResourceManager.GetString("PreferenceLabelWohnbereich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please contact admin. ähnelt.
        /// </summary>
        internal static string RegisterContactDBFailure {
            get {
                return ResourceManager.GetString("RegisterContactDBFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill out all required fields in the registration form. ähnelt.
        /// </summary>
        internal static string RegisterEmptyFields {
            get {
                return ResourceManager.GetString("RegisterEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration failed ähnelt.
        /// </summary>
        internal static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter username ähnelt.
        /// </summary>
        internal static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die REGISTRATION ähnelt.
        /// </summary>
        internal static string RegisterPageHeadline {
            get {
                return ResourceManager.GetString("RegisterPageHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your password ähnelt.
        /// </summary>
        internal static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat password ähnelt.
        /// </summary>
        internal static string RegisterPasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a user role. ähnelt.
        /// </summary>
        internal static string RegisterSelectRole {
            get {
                return ResourceManager.GetString("RegisterSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration successful ähnelt.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have successfully registered in user role 4. Please log in now. ähnelt.
        /// </summary>
        internal static string RegisterSuccessTextRoleFour {
            get {
                return ResourceManager.GetString("RegisterSuccessTextRoleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have successfully registered in user role 1. Please log in now. ähnelt.
        /// </summary>
        internal static string RegisterSuccessTextRoleOne {
            get {
                return ResourceManager.GetString("RegisterSuccessTextRoleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have successfully registered in user role 3. Please log in now. ähnelt.
        /// </summary>
        internal static string RegisterSuccessTextRoleThree {
            get {
                return ResourceManager.GetString("RegisterSuccessTextRoleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have successfully registered in user role 2. Please log in now. ähnelt.
        /// </summary>
        internal static string RegisterSuccessTextRoleTwo {
            get {
                return ResourceManager.GetString("RegisterSuccessTextRoleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username is not registered in the InQS Web System. Please use valid username. ähnelt.
        /// </summary>
        internal static string RegisterUnknownInQSUser {
            get {
                return ResourceManager.GetString("RegisterUnknownInQSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your selected role is not corresponding to the role in the InQS Web System. ähnelt.
        /// </summary>
        internal static string RegisterWrongRole {
            get {
                return ResourceManager.GetString("RegisterWrongRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration is not available until 16 September 2019. Please try again later. ähnelt.
        /// </summary>
        internal static string RegistrationNotYetAvailable {
            get {
                return ResourceManager.GetString("RegistrationNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The category cannot be reset because the evaluation period is already over. ähnelt.
        /// </summary>
        internal static string ResetCategoryImpossibleWarning {
            get {
                return ResourceManager.GetString("ResetCategoryImpossibleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to reset the category data? ähnelt.
        /// </summary>
        internal static string ResetCategoryWarning {
            get {
                return ResourceManager.GetString("ResetCategoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Role 4 ähnelt.
        /// </summary>
        internal static string RoleFour {
            get {
                return ResourceManager.GetString("RoleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Role 1 ähnelt.
        /// </summary>
        internal static string RoleOne {
            get {
                return ResourceManager.GetString("RoleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Role 3 ähnelt.
        /// </summary>
        internal static string RoleThree {
            get {
                return ResourceManager.GetString("RoleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Role 2 ähnelt.
        /// </summary>
        internal static string RoleTwo {
            get {
                return ResourceManager.GetString("RoleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Surveys ähnelt.
        /// </summary>
        internal static string ShowSurvey {
            get {
                return ResourceManager.GetString("ShowSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign In ähnelt.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data entry form for quality recording ähnelt.
        /// </summary>
        internal static string SurveyHeadline {
            get {
                return ResourceManager.GetString("SurveyHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for ähnelt.
        /// </summary>
        internal static string SurveyHeadlineFor {
            get {
                return ResourceManager.GetString("SurveyHeadlineFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data entry form without quality recording ähnelt.
        /// </summary>
        internal static string SurveyHeadlineWithoutQE {
            get {
                return ResourceManager.GetString("SurveyHeadlineWithoutQE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username is already taken. Please change username. ähnelt.
        /// </summary>
        internal static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
